repo_url: https://example.com/test/repo/
repo_name: Test Repo
repo_description: >-
  This is a repository of apps to be used with an F-Droid-compatible client.
  Applications in this repository are official binaries built by the original
  application developers.

repo_keyalias: testrepo
keystore: keystore.jks
keystorepass_cmd: cat .keystorepass
keypass_cmd: cat .keypass

aliases:
  u: update
  test:
    - lint
    - update -v
    - link
    - example

hooks:
  - name: example
    info: example hook
    config:
      count_recipes: true
      count_apks: true
